/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;
import Class.UIUtils;
import Frame.CategoriaFrame;
import Frame.CategoriaFrame;
import Frame.EventFrame;
import Frame.EventFrame;
import Frame.Login.AuthClient;
import Frame.Login.AuthClient;
import Frame.Login.loginFrame;
import Frame.Login.loginFrame;
import Frame.Panel;
import Frame.Panel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicComboBoxUI;
/**
 *
 * @author paolo
 */
public class GestionaleFrame extends javax.swing.JFrame {
    public JPanel contenitore = new JPanel();
    private String nomeutente;
    
    /**
     * Creates new form main
     */
    
    
    //TODO Aggiungere il parametro del nome utente richeisto al login, cosi da poter avere categorie e eventi SOLO dell utente.
    //TODO Modificare tutti i path e il caricamento degli eventi.
    //TODO 
    
    public GestionaleFrame(String nomeutente){ 
        this.nomeutente = nomeutente;
        initComponents(); 
        setLocationRelativeTo(null);
        init();
        UIUtils.styleAllComponents(this.getContentPane());
        openTab();
        contenitore.setLayout(new BoxLayout(contenitore, BoxLayout.Y_AXIS));
        scroll.setViewportView(contenitore);
        contenitore.removeAll();
        this.nomeutente = nomeutente;
        contenitore.setBackground(Color.decode("#FDFFFC"));
        update();
        
    }
    
    public String getUsername() {
        return nomeutente;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionale");
        setLocation(new java.awt.Point(480, 150));
        setResizable(false);

        scroll.setBackground(new java.awt.Color(51, 51, 51));
        scroll.setBorder(null);
        scroll.setForeground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(3, 83, 164));

        add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Add Evento", "Add Categoria" }));
        add.setToolTipText("seleziona");
        add.setMinimumSize(new java.awt.Dimension(115, 26));
        add.setPreferredSize(new java.awt.Dimension(115, 26));
        add.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addItemStateChanged(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/agg.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 255, 252));
        jLabel1.setText("Gestionale");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        logout.setForeground(new java.awt.Color(253, 255, 252));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(618, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 99, Short.MAX_VALUE)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addItemStateChanged
             
    }//GEN-LAST:event_addItemStateChanged

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
   
    }//GEN-LAST:event_addActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        contenitore.removeAll();
        update();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        JFrame f = new loginFrame();
        f.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed
    
   
    
    private boolean checkFile() throws FileNotFoundException {
        Vector<String> catout = AuthClient.richiediDati(nomeutente, "Categorie");
        if (catout == null || catout.isEmpty()) {
            return false;
        }
        if (catout.firstElement().trim().isEmpty()) {
            return false;
        }
        return true;
    }
    
    private void openTab() {
        
        add.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {                
                
                try {
                    if (add.getSelectedIndex() == 1 && checkFile()) {
                        EventFrame ef;
                        try {
                            ef = new EventFrame(nomeutente, GestionaleFrame.this, false);
                            ef.setVisible(true);
                        } catch (FileNotFoundException ex) {
                            System.err.println("Errore in openTab()!");
                        } catch (IOException ex) {
                            Logger.getLogger(GestionaleFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else if (add.getSelectedIndex() == 2) {
                        CategoriaFrame f = new CategoriaFrame(nomeutente);
                        f.setVisible(true);
                    }  else if (!checkFile()) {
                        JOptionPane.showMessageDialog(rootPane, "DEVI PRIMA CREARE UNA CATEGORIA!");
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GestionaleFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    public void init() {
        
        //Controllare se la cartella esiste con tutti i file all interno, se non esiste prima crea la cartella e poi crea tutti i files
        String path2 = System.getProperty("user.home") + File.separator + "Gestionale";
        System.out.println(path2);
        String pathFile1 = path2 + File.separator + "Categorie.csv";
        String pathFile2 = path2 + File.separator + "Eventi.csv";
        File file = new File(pathFile1);
        File file2 = new File(pathFile2);

        Path path = Paths.get(path2);
        if (Files.exists(path)) {
            System.out.println("La cartella esiste già.");
                            
            if (!file.exists()) {
                try{
                    file.createNewFile();
                    System.out.println("La cartella esiste gia pero il file categorie e stato appena creato!");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            //GAY
            if (!file2.exists()) {
                try {
                    file2.createNewFile();
                    System.out.println("La cartella esiste gia pero il file eveneti e stato appena creato!");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            
        } else {
            try {
                Files.createDirectories(path);
                System.out.println("Cartella creata con successo!");
                

                
                if (!file.exists()) {
                    try{
                        file.createNewFile();
                        System.out.println("File categorie creato!");
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                
                if (!file2.exists()) {
                    try {
                        file2.createNewFile();
                        System.out.println("File eventi creato!");
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }
    
    public void update() {
        contenitore.removeAll();
        Vector<String> categorie = AuthClient.richiediDati(nomeutente, "Categorie");
        for (String s : categorie) {
            System.out.println("[Cat] " + s);
        }
        Vector<String> eventi = AuthClient.richiediDati(nomeutente, "Eventi");
        for (String e : eventi) {
            System.out.println("[Evt] " + e );
        }
        addPanel(categorie, eventi);
    }
    
    public void addPanel(Vector<String> categorie, Vector<String> eventi) {
        
        //file -> Eventi
        //file2 -> Categorie
        

        for (String stringa : eventi) {


            if(!stringa.equals("")){

//                System.err.println("NON E VUOTA!");

                String splitted[] = stringa.split("\\$#=");
                String stringa2 = splitted[0] + "@#$@#" + splitted[2];
                String splitted2[] = stringa2.split(",");


                String nome = splitted2[0];
                String descrizione = splitted[1];
                String data = splitted2[2];
                String orario = splitted2[3];
                String categoria = splitted2[4];

                String colore = "#000000";

                for (String linea : categorie) {
                    String sp[] = linea.split(":\\$#:");
                    System.out.println("Categoria: " + sp[0]);
                    System.out.println("Colore: " + sp[1]);

                    if (categoria.trim().equalsIgnoreCase(sp[0].trim())) {
                        colore = sp[1].trim();
                    }
                }

                contenitore.add(Box.createRigidArea(new Dimension(0, 10)));
                contenitore.add(new Panel(nome,descrizione,data,orario,categoria,colore, contenitore, GestionaleFrame.this));

                System.out.println(stringa);

            }else{

                break;

            }
            contenitore.revalidate();
            contenitore.repaint();
        }   
    }
        

    
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
} 
