/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;


import static Class.UIUtils.styleButton;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Box;
import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author paolo
 */
public class Panel extends javax.swing.JPanel {
    
    public String c ;
    public JPanel contenitore;
    
    /**
     * Creates new form Panel
     */
    public Panel(String n , String d , String dat , String o , String ca ,String color, JPanel contenitore) {
        initComponents();
        styleButton(Del);
        nome.setText(n);
        descrizione.setText(d);
        data.setText(dat);
        ora.setText(o);
        categoria.setText(ca); 
        this.c = color;
        this.contenitore = contenitore;
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
//        descrizione.setBackground(new Color(Color.decode(c).getRed(), Color.decode(c).getGreen(), Color.decode(c).getBlue(), 90));
        Del.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                
                contenitore.remove(Panel.this);
                contenitore.revalidate();
                contenitore.repaint();

                String path2 = System.getProperty("user.home") + File.separator + "Gestionale" + File.separator + "Eventi.csv";
                
                eliminaEventoDaCSV(path2, n, d, dat, o, ca, color);
            }
        });
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        
        // Abilitare l'anti-aliasing per linee più lisce
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Impostare il colore di sfondo
        g2d.setColor(new Color(Color.decode(c).getRed(), Color.decode(c).getGreen(), Color.decode(c).getBlue(), 130));
        g2d.fillRoundRect(10, 10, getWidth() - 20, getHeight() - 20, 30, 30);
        
        // Impostare il colore del bordo
        g2d.setColor(Color.BLACK);
        
        // Disegnare il bordo del rettangolo stondato (solo contorno)
        g2d.setStroke(new BasicStroke(1)); // Imposta lo spessore del bordo a 1px
        g2d.drawRoundRect(10, 10, getWidth() - 20, getHeight() - 20, 30, 30);
    }
    
    public static void eliminaEventoDaCSV(String percorsoFile, String nome, String descrizione, String data, String ora, String categoria, String colore) {
        File file = new File(percorsoFile);
        File tempFile = new File("temp.csv");

        boolean eliminato = false;

        try (
            BufferedReader reader = new BufferedReader(new FileReader(file));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))
        ) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parti = line.split(",");

                // Confronto rigoroso: se tutti i campi combaciano ed è il primo match, salta questa riga
                if (!eliminato && parti.length >= 6 &&
                    parti[0].equals(nome) &&
                    parti[1].equals(descrizione) &&
                    parti[2].equals(data) &&
                    parti[3].equals(ora) &&
                    parti[4].equals(categoria) &&
                    parti[5].equals(colore)) {
                    eliminato = true;
                    continue; // non scrivere questa riga
                }

                writer.write(line);
                writer.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Sostituisci il file originale con quello aggiornato
        if (file.delete()) {
            tempFile.renameTo(file);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrizione = new javax.swing.JTextArea();
        Del = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel8.setText("jLabel8");

        setMaximumSize(new java.awt.Dimension(760, 150));
        setMinimumSize(new java.awt.Dimension(760, 150));
        setPreferredSize(new java.awt.Dimension(760, 150));

        nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nome.setText("Nome");

        jLabel2.setText("Descrizione:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Data:");

        data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data.setText("12-09-2025");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Orario:");

        ora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ora.setText("99:99");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Categoria:");

        categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoria.setText("{categoria}");

        descrizione.setColumns(20);
        descrizione.setRows(5);
        jScrollPane1.setViewportView(descrizione);

        Del.setBackground(new java.awt.Color(238, 238, 238));
        Del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/cestino.png"))); // NOI18N
        Del.setBorder(null);
        Del.setMaximumSize(new java.awt.Dimension(76, 35));
        Del.setMinimumSize(new java.awt.Dimension(76, 35));
        Del.setPreferredSize(new java.awt.Dimension(76, 35));
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ora, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Del, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(data))
                    .addComponent(Del, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ora))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(categoria))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel data;
    private javax.swing.JTextArea descrizione;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel ora;
    // End of variables declaration//GEN-END:variables
}
