/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;


import static Class.UIUtils.styleButton;
import Frame.Login.AuthClient;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author paolo
 */
public class Panel extends javax.swing.JPanel {
    
    public String c ;
    public JPanel contenitore;
    private String nome_;
    private String descrizione_;
    private String data_;
    private String orario_;
    private String categoria_;
    private GestionaleFrame f;
    
    /**
     * Creates new form Panel
     */
    public Panel(String n , String d , String dat , String o , String ca ,String color, JPanel contenitore, GestionaleFrame f) {
        initComponents();
        styleButton(Del);
        this.nome_ = n;
        this.descrizione_ = d;
        this.data_ = dat;
        this.orario_ = o;
        this.categoria_ = ca;
        this.f = f;
        nome.setText(n);
        descrizione.setText(d);
        data.setText(dat);
        ora.setText(o);
        categoria.setText(ca); 
        this.c = color;
        this.contenitore = contenitore;
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
//        descrizione.setBackground(new Color(Color.decode(c).getRed(), Color.decode(c).getGreen(), Color.decode(c).getBlue(), 90));
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        
        // Abilitare l'anti-aliasing per linee più lisce
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Impostare il colore di sfondo
        g2d.setColor(new Color(Color.decode(c).getRed(), Color.decode(c).getGreen(), Color.decode(c).getBlue(), 130));
        g2d.fillRoundRect(10, 10, getWidth() - 20, getHeight() - 20, 30, 30);
        
        // Impostare il colore del bordo
        g2d.setColor(Color.BLACK);
        
        // Disegnare  bordo del rettangolo stondato (solo contorno)
        g2d.setStroke(new BasicStroke(1)); // Imposta lo spessore del bordo a 1px
        g2d.drawRoundRect(10, 10, getWidth() - 20, getHeight() - 20, 30, 30);
    }
    
//    public static void eliminaEventoDaCSV(String percorsoFile, String nome, String descrizione, String data, String ora, String categoria, String colore) {
//        File file = new File(percorsoFile);
//        File tempFile = new File("temp.csv");
//
//        boolean eliminato = false;
//
//        try (
//            BufferedReader reader = new BufferedReader(new FileReader(file));
//            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))
//        ) {
//            String line;
//            while ((line = reader.readLine()) != null) {
//                String[] parti = line.split(",");
//
//                // Confronto rigoroso: se tutti i campi combaciano ed è il primo match, salta questa riga
//                if (!eliminato && parti.length >= 6 &&
//                    parti[0].equals(nome) &&
//                    parti[1].equals(descrizione) &&
//                    parti[2].equals(data) &&
//                    parti[3].equals(ora) &&
//                    parti[4].equals(categoria) &&
//                    parti[5].equals(colore)) {
//                    eliminato = true;
//                    continue; // non scrivere questa riga
//                }
//
//                writer.write(line);
//                writer.newLine();
//            }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//
//        // Sostituisci il file originale con quello aggiornato
//        if (file.delete()) {
//            tempFile.renameTo(file);
//        }
//    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrizione = new javax.swing.JTextArea();
        Del = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel8.setText("jLabel8");

        setMaximumSize(new java.awt.Dimension(760, 150));
        setMinimumSize(new java.awt.Dimension(760, 150));
        setPreferredSize(new java.awt.Dimension(760, 150));

        nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nome.setText("Nome");

        jLabel2.setText("Descrizione:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Data:");

        data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data.setText("12-09-2025");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Orario:");

        ora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ora.setText("99:99");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Categoria:");

        categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoria.setText("{categoria}");

        descrizione.setEditable(false);
        descrizione.setColumns(20);
        descrizione.setLineWrap(true);
        descrizione.setRows(5);
        jScrollPane1.setViewportView(descrizione);

        Del.setBackground(new java.awt.Color(255, 255, 255));
        Del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/cestino.png"))); // NOI18N
        Del.setBorder(null);
        Del.setMaximumSize(new java.awt.Dimension(76, 35));
        Del.setMinimumSize(new java.awt.Dimension(76, 35));
        Del.setPreferredSize(new java.awt.Dimension(76, 35));
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/edit-button.png"))); // NOI18N
        editButton.setBorder(null);
        editButton.setMaximumSize(new java.awt.Dimension(76, 35));
        editButton.setMinimumSize(new java.awt.Dimension(76, 35));
        editButton.setPreferredSize(new java.awt.Dimension(76, 35));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ora, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Del, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(data))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(ora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(categoria)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        String user = f.getUsername();
        String nom = nome_;
        String desc = "$#=" + descrizione_ + "$#=";
        String dataa = data_;
        String or = orario_;
        String c = categoria_;
        String evento = nom + "," + desc + "," + dataa + "," + or + "," + c;
        System.out.println(evento);
                
        boolean succes = AuthClient.inviaDati("DELETE", user, evento);
        if (succes) {
            JOptionPane.showMessageDialog(this, "Evento eliminato!");
            setVisible(false);
            f.update();
        } else {
            JOptionPane.showMessageDialog(this, "Evento non eliminato!");
        }
        
    }//GEN-LAST:event_DelActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try {
            EventFrame e = new EventFrame(nome_, descrizione_, data_, orario_, categoria_, f.getUsername(), f, true);
            e.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel data;
    private javax.swing.JTextArea descrizione;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel ora;
    // End of variables declaration//GEN-END:variables
}
